In [2]:
import numpy as np
import pandas as pd
from glob import glob
import datetime
from pyproj import Transformer
import matplotlib.pyplot as plt
# import wradlib as wrl
import re

URL_weather_data = 'C:/Users/sverrirhd/Google Drive/Sk√≥li/DTU/Thesis/Data/'

In [3]:
df_temp_long = pd.read_csv(URL_weather_data + 'Temperature data/hbs_hitastig_klst.csv',sep='\t')
df_temp_long.loc[:,'TIMI'] = pd.to_datetime(df_temp_long.loc[:,'TIMI'])
df_temp_long.loc[:,'T'] = df_temp_long.loc[:,'T'].replace({'(null)':np.nan}).astype(float)
df_temp_long.STOD = df_temp_long.STOD.astype('str')
df_temp = df_temp_long.pivot_table(values='T',index='TIMI',columns='STOD')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

In [45]:
df_temp.to_pickle('temperature_data.pkl')

In [33]:
df_temp_long.T = df_temp_long.T.astype('float')

TypeError: float() argument must be a string or a number, not 'Timestamp'

In [29]:
df_temp_long.pivot_table(values='T',index='TIMI',columns='STOD')

C:\Users\sverrirhd\AppData\Roaming\Python\Python39\site-packages\pandas\core\apply.py:507: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  return self._try_aggregate_string_function(obj, f, *self.args, **self.kwargs)

Empty DataFrame
Columns: []
Index: [2011-01-01 01:00:00, 2011-01-01 02:00:00, 2011-01-01 03:00:00, 2011-01-01 04:00:00, 2011-01-01 05:00:00, 2011-01-01 06:00:00, 2011-01-01 07:00:00, 2011-01-01 08:00:00, 2011-01-01 09:00:00, 2011-01-01 10:00:00, 2011-01-01 11:00:00, 2011-01-01 12:00:00, 2011-01-01 13:00:00, 2011-01-01 14:00:00, 2011-01-01 15:00:00, 2011-01-01 16:00:00, 2011-01-01 17:00:00, 2011-01-01 18:00:00, 2011-01-01 19:00:00, 2011-01-01 20:00:00, 2011-01-01 21:00:00, 2011-01-01 22:00:00, 2011-01-01 23:00:00, 2011-01-02 00:00:00, 2011-01-02 01:00:00, 2011-01-02 02:00:00, 2011-01-02 03:00:00, 2011-01-02 04:00:00, 2011-01-02 05:00:00, 2011-01-02 06:00:00, 2011-01-02 07:00:00, 2011-01-02 08:00:00, 2011-01-02 09:00:00, 2011-01-02 10:00:00, 2011-01-02 11:00:00, 2011-01-02 12:00:00, 2011-01-02 13:00:00, 2011-01-02 14:00:00, 2011-01-02 15:00:00, 2011-01-02 16:00:00, 2011-01-02 17:00:00, 2011-01-02 18:00:00, 2011-01-02 19:00:00, 2011-01-02 20:00:00, 2011-01-02 21:00:00, 2011-01-02 22:00:00, 2011-01-02 23:00:00, 2011-01-03 00:00:00, 2011-01-03 01:00:00, 2011-01-03 02:00:00, 2011-01-03 03:00:00, 2011-01-03 04:00:00, 2011-01-03 05:00:00, 2011-01-03 06:00:00, 2011-01-03 07:00:00, 2011-01-03 08:00:00, 2011-01-03 09:00:00, 2011-01-03 10:00:00, 2011-01-03 11:00:00, 2011-01-03 12:00:00, 2011-01-03 13:00:00, 2011-01-03 14:00:00, 2011-01-03 15:00:00, 2011-01-03 16:00:00, 2011-01-03 17:00:00, 2011-01-03 18:00:00, 2011-01-03 19:00:00, 2011-01-03 20:00:00, 2011-01-03 21:00:00, 2011-01-03 22:00:00, 2011-01-03 23:00:00, 2011-01-04 00:00:00, 2011-01-04 01:00:00, 2011-01-04 02:00:00, 2011-01-04 03:00:00, 2011-01-04 04:00:00, 2011-01-04 05:00:00, 2011-01-04 06:00:00, 2011-01-04 07:00:00, 2011-01-04 08:00:00, 2011-01-04 09:00:00, 2011-01-04 10:00:00, 2011-01-04 11:00:00, 2011-01-04 12:00:00, 2011-01-04 13:00:00, 2011-01-04 14:00:00, 2011-01-04 15:00:00, 2011-01-04 16:00:00, 2011-01-04 17:00:00, 2011-01-04 18:00:00, 2011-01-04 19:00:00, 2011-01-04 20:00:00, 2011-01-04 21:00:00, 2011-01-04 22:00:00, 2011-01-04 23:00:00, 2011-01-05 00:00:00, 2011-01-05 01:00:00, 2011-01-05 02:00:00, 2011-01-05 03:00:00, 2011-01-05 04:00:00, ...]

[93998 rows x 0 columns]

In [28]:
df_temp#_long.columns

Empty DataFrame
Columns: []
Index: [2011-01-01 01:00:00, 2011-01-01 02:00:00, 2011-01-01 03:00:00, 2011-01-01 04:00:00, 2011-01-01 05:00:00, 2011-01-01 06:00:00, 2011-01-01 07:00:00, 2011-01-01 08:00:00, 2011-01-01 09:00:00, 2011-01-01 10:00:00, 2011-01-01 11:00:00, 2011-01-01 12:00:00, 2011-01-01 13:00:00, 2011-01-01 14:00:00, 2011-01-01 15:00:00, 2011-01-01 16:00:00, 2011-01-01 17:00:00, 2011-01-01 18:00:00, 2011-01-01 19:00:00, 2011-01-01 20:00:00, 2011-01-01 21:00:00, 2011-01-01 22:00:00, 2011-01-01 23:00:00, 2011-01-02 00:00:00, 2011-01-02 01:00:00, 2011-01-02 02:00:00, 2011-01-02 03:00:00, 2011-01-02 04:00:00, 2011-01-02 05:00:00, 2011-01-02 06:00:00, 2011-01-02 07:00:00, 2011-01-02 08:00:00, 2011-01-02 09:00:00, 2011-01-02 10:00:00, 2011-01-02 11:00:00, 2011-01-02 12:00:00, 2011-01-02 13:00:00, 2011-01-02 14:00:00, 2011-01-02 15:00:00, 2011-01-02 16:00:00, 2011-01-02 17:00:00, 2011-01-02 18:00:00, 2011-01-02 19:00:00, 2011-01-02 20:00:00, 2011-01-02 21:00:00, 2011-01-02 22:00:00, 2011-01-02 23:00:00, 2011-01-03 00:00:00, 2011-01-03 01:00:00, 2011-01-03 02:00:00, 2011-01-03 03:00:00, 2011-01-03 04:00:00, 2011-01-03 05:00:00, 2011-01-03 06:00:00, 2011-01-03 07:00:00, 2011-01-03 08:00:00, 2011-01-03 09:00:00, 2011-01-03 10:00:00, 2011-01-03 11:00:00, 2011-01-03 12:00:00, 2011-01-03 13:00:00, 2011-01-03 14:00:00, 2011-01-03 15:00:00, 2011-01-03 16:00:00, 2011-01-03 17:00:00, 2011-01-03 18:00:00, 2011-01-03 19:00:00, 2011-01-03 20:00:00, 2011-01-03 21:00:00, 2011-01-03 22:00:00, 2011-01-03 23:00:00, 2011-01-04 00:00:00, 2011-01-04 01:00:00, 2011-01-04 02:00:00, 2011-01-04 03:00:00, 2011-01-04 04:00:00, 2011-01-04 05:00:00, 2011-01-04 06:00:00, 2011-01-04 07:00:00, 2011-01-04 08:00:00, 2011-01-04 09:00:00, 2011-01-04 10:00:00, 2011-01-04 11:00:00, 2011-01-04 12:00:00, 2011-01-04 13:00:00, 2011-01-04 14:00:00, 2011-01-04 15:00:00, 2011-01-04 16:00:00, 2011-01-04 17:00:00, 2011-01-04 18:00:00, 2011-01-04 19:00:00, 2011-01-04 20:00:00, 2011-01-04 21:00:00, 2011-01-04 22:00:00, 2011-01-04 23:00:00, 2011-01-05 00:00:00, 2011-01-05 01:00:00, 2011-01-05 02:00:00, 2011-01-05 03:00:00, 2011-01-05 04:00:00, ...]

[93998 rows x 0 columns]

In [5]:
df = pd.read_csv(URL_weather_data + 'Weather data 2020/from 2016 sept observations.csv')
df.head(3)

,date_time,station_id,temperature,temperature_max,temperature_min,rain_fall,snow_depth,dew_point,moist_pressure,moist,...,humidity,cloud_coverage,total_sun_radiation,total_sun_radiatio_ max,reflection_of_sun_radiation_from_earth,reflection_of_sun_radiation_from_earth_max,infrared_radiation_from_sky,infrared_radiation_from_sky_max,infrared_radiation_from_earth,infrared_radiation_from_earth_max
0,2016-10-29 00:00:00.000,1473,3.0,3.0,2.2,NaN,NaN,-1.0,5.7,76.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,2016-10-29 00:00:00.000,1475,1.8,1.9,1.5,NaN,NaN,-2.1,5.3,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,2016-10-29 00:00:00.000,1477,2.0,2.0,1.9,NaN,NaN,-2.0,5.3,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [3]:
df.station_id.value_counts()

1475    42831
1477    42828
1481    42795
1473    42761
7476    42323
1479    29394
Name: station_id, dtype: int64

In [4]:
# Check how much NAN data is in each column for each station (checking which stations have certain observations)
name_dict = {
    1481 : 'H√≥lmshei√∞i',
    1475 : 'Reykjav√≠k',
    7475 : 'Reykjav√≠k b√∫ve√∞urst√∂√∞',
    1 : 'Reykjav√≠k',
    1473 : 'Straumsv√≠k',
    1479 : 'Korpa',
    7476 : 'Reykjav√≠k s√≥lgeislun',
    1477 : 'Reykjav√≠kurflugv√∂llur',
    6208 : '√ûykkvib√¶r',
}
df.groupby('station_id').apply(lambda x : (~x.isna()).sum()/len(x)).T.round(2).rename(lambda x:name_dict[x] + ' ' + str(x),axis='columns',inplace=False)
# df.groupby('station_id').apply(lambda x : (~x.isna()).sum()/len(x)).T.round(2)

station_id,Straumsv√≠k 1473,Reykjav√≠k 1475,Reykjav√≠kurflugv√∂llur 1477,Korpa 1479,H√≥lmshei√∞i 1481,Reykjav√≠k s√≥lgeislun 7476
date_time,1.0,1.0,1.0,1.0,1.0,1.0
station_id,1.0,1.0,1.0,1.0,1.0,1.0
temperature,1.0,1.0,1.0,1.0,1.0,0.0
temperature_max,1.0,1.0,1.0,1.0,1.0,0.0
temperature_min,1.0,1.0,1.0,1.0,1.0,0.0
rain_fall,0.0,0.0,0.0,0.0,0.0,0.0
snow_depth,0.0,0.0,0.0,0.0,0.0,0.0
dew_point,1.0,1.0,1.0,0.0,1.0,0.0
moist_pressure,1.0,1.0,1.0,0.0,1.0,0.0
moist,1.0,1.0,1.0,0.0,1.0,0.0
wind_direction,1.0,1.0,1.0,1.0,1.0,0.0
wind_speed,1.0,1.0,1.0,1.0,1.0,0.0
max_wind,1.0,1.0,1.0,1.0,1.0,0.0
gust,0.0,0.0,0.0,0.0,0.0,0.0
humidity,0.0,0.0,0.0,0.0,0.0,0.0
cloud_coverage,0.0,0.0,0.0,0.0,0.0,0.0
total_sun_radiation,0.0,0.0,0.0,1.0,0.0,1.0
total_sun_radiatio_ max,0.0,0.0,0.0,1.0,0.0,1.0
reflection_of_sun_radiation_from_earth,0.0,0.0,0.0,0.0,0.0,1.0
reflection_of_sun_radiation_from_earth_max,0.0,0.0,0.0,0.0,0.0,1.0
infrared_radiation_from_sky,0.0,0.0,0.0,0.0,0.0,1.0
infrared_radiation_from_sky_max,0.0,0.0,0.0,0.0,0.0,1.0
infrared_radiation_from_earth,0.0,0.0,0.0,0.0,0.0,1.0
infrared_radiation_from_earth_max,0.0,0.0,0.0,0.0,0.0,1.0

In [5]:
df_rvk = df.loc[df.station_id.isin([1475,7476])]

In [8]:
temperature = pd.pivot_table(df_rvk,values='temperature',index='date_time',columns='station_id').iloc[:,0]
temperature_min = pd.pivot_table(df_rvk,values='temperature_min',index='date_time',columns='station_id').iloc[:,0]
temperature_max = pd.pivot_table(df_rvk,values='temperature_max',index='date_time',columns='station_id').iloc[:,0]
radiation = pd.pivot_table(df_rvk,values='total_sun_radiation',index='date_time',columns='station_id').iloc[:,0]
moist_pressure = pd.pivot_table(df_rvk,values='moist_pressure',index='date_time',columns='station_id').iloc[:,0]

In [9]:
column_names = ['temperature','temperature_min','temperature_max','radiation','moist_pressure']
df_input = pd.DataFrame([temperature,temperature_min,temperature_max,radiation,moist_pressure],index=column_names).T

In [11]:
df_input.index = pd.DatetimeIndex(df_input.index)
df_input = df_input.resample('1h').interpolate(method='linear')
df_input.to_pickle('weather_data')